package com.carbon.prolocker.ad

object AdPlacement {

    const val HOME_TAB_APPS = "HOME_TAB_APPS"
    const val HOME_TAB_THEMES = "HOME_TAB_THEMES"
    const val HOME_TAB_SETTINGS = "HOME_TAB_SETTINGS"

    const val LOCKSCREEN_TOP = "LOCKSCREEN_TOP"
    const val LOCKSCREEN_BOTTOM = "LOCKSCREEN_BOTTOM"

    const val RAM_CLEANER_NATIVE = "RAM_CLEANER_NATIVE"

    const val BACKGROUND_LIST_NATIVE = "BACKGROUND_LIST_NATIVE"
    const val BACKGROUND_PREVIEW_NATIVE = "BACKGROUND_PREVIEW_NATIVE"

    const val EXIT_NATIVE = "EXIT_NATIVE"

    const val INTERSTITIAL_BACKGROUND = "INTERSTITIAL_BACKGROUND"
    const val INTERSTITIAL_RAM_CLEANER = "INTERSTITIAL_RAM_CLEANER"
}
